### ISSUE TITLE
Installation failed on laravel v8

### ISSUE THREAD

**Issue by prafullaranjan** [JackieDo/laravel-packager#3]
Hi there, Just tried to install this package and got the below errors, seems in-compatibility.

- C:\xampp\htdocs>composer require jackiedo/laravel-packager

- Using version ^1.0 for jackiedo/laravel-packager
- ./composer.json has been updated
- Running composer update jackiedo/laravel-packager
- Loading composer repositories with package information
- Updating dependencies

Your requirements could not be resolved to an installable set of packages.

  `Problem 1
    - jackiedo/laravel-packager[1.0.0, ..., 1.0.2] require illuminate/filesystem ^5.1|^6.0|^7.0 -> found illuminate/filesystem[v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.
    - Root composer.json requires jackiedo/laravel-packager ^1.0 -> satisfiable by jackiedo/laravel-packager[1.0.0, 1.0.1, 1.0.2].`

Is there any way to fix this?

**Comment by JackieDo** [comment]
@prafullaranjan : Added support for Laravel 8.x  (from the release [1.0.3](https://github.com/JackieDo/laravel-packager/releases/tag/1.0.3))

**Comment by prafullaranjan** [comment]
Thanks for this, much appreciated. Is it possible to also use this with
laravel 9? I haven't tried it yet.

**Comment by JackieDo** [comment]
@prafullaranjan :
> Thanks for this, much appreciated. Is it possible to also use this with laravel 9? I haven't tried it yet.

Currently, it only supports Laravel 8.x. I am adding some features to support Laravel 9.x

**Comment by JackieDo** [comment]
@prafullaranjan :

This package now supports Laravel 9.x (from the relase [1.0.4](https://github.com/JackieDo/laravel-packager/releases/tag/1.0.4))

**Comment by prafullaranjan** [comment]
This is working fine as expected. Thanks for this update, I'm  using laravel 9 (latest version as of today).

Package is getting created successfully but not able to automatically installed, got this message after success.

`Your package was created successfully but there was an error during the installation process. `

**Comment by JackieDo** [comment]
> This is working fine as expected. Thanks for this update, I'm using laravel 9 (latest version as of today).
> 
> Package is getting created successfully but not able to automatically installed, got this message after success.
> 
> `Your package was created successfully but there was an error during the installation process. `

@prafullaranjan :

Dear friend!
I proceeded to install Laravel 9x (latest version as you mentioned) and tried to run the create package command as follows:

```shell
$ php artisan packager:new jackiedo/first-package --resources --install
```
And the result is perfect, without any errors.

I don't know if your platform versions are the same as mine. I post my PHP, Laravel and this package version information that i installed for your reference.

> **Laravel** version:

```shell
D:\www\laravel-9x.local>php artisan --version
Laravel Framework 9.5.1
```

> **Laravel Packager** version:

```shell
D:\www\laravel-9x.local>composer show jackiedo/laravel-packager
name     : jackiedo/laravel-packager
descrip. : A CLI tool to create packages for Laravel application.
keywords : Skeleton, builder, generator, laravel, package, packer
versions : * 1.0.9
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage :
source   : [git] https://github.com/JackieDo/laravel-packager.git 1613450ccf99ffa46617093a739b0a6a6e98bd8d
dist     : [zip] https://api.github.com/repos/JackieDo/laravel-packager/zipball/1613450ccf99ffa46617093a739b0a6a6e98bd8d 1613450ccf99ffa46617093a739b0a6a6e98bd8d
path     : D:\www\laravel-9x.local\vendor\jackiedo\laravel-packager
names    : jackiedo/laravel-packager

support
issues : https://github.com/JackieDo/laravel-packager/issues
source : https://github.com/JackieDo/laravel-packager/tree/1.0.9

autoload
files
psr-4
Jackiedo\Packager\ => src

requires
illuminate/console ^5.1|^6.0|^7.0|^8.0|^9.0
illuminate/filesystem ^5.1|^6.0|^7.0|^8.0|^9.0
illuminate/support ^5.1|^6.0|^7.0|^8.0|^9.0
jackiedo/path-helper ^1.0
php >=5.4.0
```

> **PHP** version:

```shell
D:\www\laravel-9x.local>php --version
PHP 8.1.2 (cli) (built: Jan 19 2022 10:18:23) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

D:\www\laravel-9x.local>
```

You see, I'm using PHP 8.1.2, Laravel 9.5.1 and version 1.0.9 of this package. Please check this information on your computer and let me know.

**Comment by JackieDo** [comment]
@prafullaranjan :

I also tested on PHP 8.0 platform. Everything is still perfect

```shell
D:\www\laravel-9x.local>php --version
PHP 8.0.9 (cli) (built: Jul 29 2021 14:12:19) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.9, Copyright (c) Zend Technologies

D:\www\laravel-9x.local>
```
